import {createRepository} from './repository.js';
import {VAPID_PUBLIC_KEY} from './config.js';
import {subscribeToRoomRequests} from './realtime.js';
import {detectPushCapability,subscribeForPush,serializeSubscription} from './notifications.js';
import {parsePrice,formatStatus,canApprove,canResubmit,canMarkPurchased,validateRequest} from './domain.js';
const app=document.querySelector('#app'),toastRoot=document.querySelector('#toast-root');let repo,state={user:null,room:null,requests:[],tab:'mine',filter:'all'},files=[],rt=null,sw=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>'¥'+Number(n||0).toLocaleString('zh-CN',{maximumFractionDigits:2}),date=s=>new Date(s).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}),toast=t=>{let e=document.createElement('div');e.className='toast';e.textContent=t;toastRoot.append(e);setTimeout(()=>e.remove(),2200)};
async function boot(){try{repo=await createRepository();state.user=await repo.init();state.room=await repo.getRoom();if(!state.user||!state.room)return onboarding();sw='serviceWorker'in navigator?await navigator.serviceWorker.register('./sw.js').catch(()=>null):null;await refresh(false);startRealtime();render();setInterval(()=>document.visibilityState==='visible'&&refresh(),60000)}catch(e){app.innerHTML=`<div class="page"><h1>连接失败</h1><p>${esc(e.message)}</p><button class="btn primary" onclick="location.reload()">重试</button></div>`}}
async function refresh(draw=true){state.requests=await repo.listRequests();if(draw)render()}
function startRealtime(){rt?.unsubscribe?.();rt=subscribeToRoomRequests({supabase:repo.supabase,roomId:state.room.id,onChange:()=>refresh()})}
function render(){let pending=state.requests.filter(r=>r.submitter_id!==state.user.id&&r.status==='pending').length;app.innerHTML=`<div class="page">${state.tab==='mine'?mine():state.tab==='approval'?approval():settings()}</div><nav class="nav"><button data-tab="mine" class="${state.tab==='mine'?'on':''}">▣<br>我的申请</button><button data-tab="approval" class="${state.tab==='approval'?'on':''}">✓${pending?' '+pending:''}<br>待我审批</button><button data-tab="settings" class="${state.tab==='settings'?'on':''}">♙<br>我的</button></nav>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()});document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(b.dataset.detail));document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>approve(b.dataset.approve));document.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>reject(b.dataset.reject));document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;render()});document.querySelector('#add')?.addEventListener('click',addForm);document.querySelector('#copy')?.addEventListener('click',async()=>{await navigator.clipboard.writeText(state.room.code);toast('邀请码已复制')});document.querySelector('#push')?.addEventListener('click',enablePush);document.querySelector('#logout')?.addEventListener('click',async()=>{await repo.leaveRoom();location.reload()})}
function mine(){let all=state.requests.filter(r=>r.submitter_id===state.user.id),list=state.filter==='all'?all:all.filter(r=>r.status===state.filter);return`<div class="top"><div><h1 class="title">我的申请</h1><div class="muted">我提交的，等待朋友审批</div></div><button class="plus" id="add">＋</button></div><div class="tabs">${[['all','全部'],['pending','待审批'],['approved','已通过'],['rejected','已驳回']].map(([k,v])=>`<button data-filter="${k}" class="${state.filter===k?'on':''}">${v}</button>`).join('')}</div>${list.length?list.map(card).join(''):'<div class="empty">还没有申请<br><small>点右上角＋提交想买的东西</small></div>'}`}
function card(r){let img=r.images?.[0]||'';return`<div class="card" data-detail="${r.id}"><div class="row">${img?`<img class="thumb" src="${esc(img)}">`:''}<div class="grow"><div class="head"><div class="name">${esc(r.product_name)}</div><div class="price">${money(r.price)}</div></div><div class="reason">${esc(r.reason)}</div><div class="meta"><span class="${r.status}">${formatStatus(r.status)}</span><span>${date(r.created_at)}</span></div></div></div></div>`}
function approval(){let p=state.requests.filter(r=>r.submitter_id!==state.user.id&&r.status==='pending');return`<div class="top"><div><h1 class="title">待我审批</h1><div class="muted">朋友提交的，等你来决定</div></div></div>${p.length?p.map(r=>`<div class="card"><div data-detail="${r.id}">${card(r)}</div><div class="actions"><button class="btn danger" data-reject="${r.id}">× 驳回</button><button class="btn approve" data-approve="${r.id}">✓ 通过</button></div></div>`).join(''):'<div class="empty">没有待审批的东西</div>'}`}
function pushInfo(){let c=detectPushCapability({navigator,Notification:globalThis.Notification,PushManager:globalThis.PushManager,ServiceWorkerRegistration:globalThis.ServiceWorkerRegistration});if(!c.supported)return{t:'当前 vivo 浏览器不支持后台推送；网页打开时仍会实时同步',b:false};if(Notification.permission==='granted')return{t:'后台通知已开启',b:false};if(Notification.permission==='denied')return{t:'通知权限已被浏览器关闭，请在浏览器设置中重新允许',b:false};return{t:'开启后，网页关闭时也可接收审批提醒',b:true}}
function settings(){let p=pushInfo();return`<div class="top"><div><h1 class="title">我的</h1><div class="muted">${esc(state.room.name)}</div></div></div><div class="card setting"><div><b>${esc(state.user.nickname)}</b><div class="muted">你的昵称</div></div></div><div class="card setting"><div><b>房间邀请码</b><div class="code">${esc(state.room.code)}</div></div><button class="btn secondary" id="copy">复制</button></div><div class="card setting"><div><b>实时同步</b><div class="muted">已连接；断线时每 60 秒兜底刷新</div></div></div><div class="card setting"><div><b>后台通知</b><div class="muted">${p.t}</div></div>${p.b?'<button class="btn secondary" id="push">开启</button>':''}</div><div class="card setting"><b>退出当前房间</b><button class="btn danger" id="logout">退出</button></div>`}
function onboarding(){app.innerHTML=`<div class="onboard"><div class="box"><h1>两个人的购物审批</h1><p class="muted">云端同步已自动连接。</p><div class="choices"><button class="choice" id="create"><strong>创建购物房间</strong><span class="muted">创建后把 6 位邀请码发给朋友</span></button><button class="choice" id="join"><strong>加入购物房间</strong><span class="muted">输入朋友的邀请码</span></button></div></div></div>`;document.querySelector('#create').onclick=()=>roomForm(true);document.querySelector('#join').onclick=()=>roomForm(false)}
function modal(html){let e=document.createElement('div');e.className='modal-bg';e.innerHTML=`<div class="modal">${html}</div>`;document.body.append(e);e.onclick=x=>{if(x.target===e)e.remove()};return e}
function roomForm(create){let m=modal(`<h2>${create?'创建购物房间':'加入购物房间'}</h2><div class="field"><label>你的昵称</label><input class="input" id="nick"></div>${create?'<div class="field"><label>房间名称</label><input class="input" id="rname" value="我和朋友的购物审批"></div>':'<div class="field"><label>邀请码</label><input class="input" id="rcode" maxlength="6"></div>'}<button class="btn primary full" id="go">${create?'创建':'加入'}</button>`);m.querySelector('#go').onclick=async()=>{let nick=m.querySelector('#nick').value.trim();if(!nick)return toast('请输入昵称');try{let r=create?await repo.createRoom(nick,m.querySelector('#rname').value.trim()):await repo.joinRoom(nick,m.querySelector('#rcode').value.trim());state.user=r.user;state.room=r.room;m.remove();await refresh(false);startRealtime();render()}catch(e){toast(e.message||'操作失败')}}}
function addForm(){files=[];let m=modal(`<h2>我要买这个</h2><div class="field"><label>商品图片 *</label><input id="pics" type="file" accept="image/*" multiple></div><div class="field"><label>商品名称 *</label><input class="input" id="name"></div><div class="field"><label>价格 *</label><input class="input" id="price" inputmode="decimal"></div><div class="field"><label>为什么想买？ *</label><textarea class="textarea" id="reason" maxlength="200"></textarea></div><div class="field"><label>商品链接（可选）</label><input class="input" id="link" type="url"></div><button class="btn primary full" id="submit">提交给朋友审批</button>`);m.querySelector('#pics').onchange=e=>files=[...e.target.files].slice(0,3);m.querySelector('#submit').onclick=async()=>{let d={images:files,name:m.querySelector('#name').value,price:m.querySelector('#price').value,reason:m.querySelector('#reason').value,link:m.querySelector('#link').value},v=validateRequest(d);if(!v.valid)return toast(Object.values(v.errors)[0]);try{let r=await repo.createRequest({name:d.name,price:parsePrice(d.price),reason:d.reason,link:d.link,files});await notify(r.id,'submitted');m.remove();toast('已提交');await refresh()}catch(e){toast(e.message||'提交失败')}}}
async function approve(id){let r=state.requests.find(x=>x.id===id);if(!r||!canApprove(r.status))return;try{await repo.approveRequest(id);await notify(id,'approved');toast('已通过');await refresh()}catch(e){toast(e.message)}}
function reject(id){let m=modal(`<h2>驳回原因</h2><textarea class="textarea" id="reason" placeholder="例如：太贵了 / 现在不需要"></textarea><button class="btn danger full" id="go">确认驳回</button>`);m.querySelector('#go').onclick=async()=>{let reason=m.querySelector('#reason').value.trim();try{await repo.rejectRequest(id,reason);await notify(id,'rejected');m.remove();toast('已驳回');await refresh()}catch(e){toast(e.message)}}}
function detail(id){let r=state.requests.find(x=>x.id===id);if(!r)return;let m=modal(`<h2>${esc(r.product_name)}</h2>${r.images?.map(x=>`<img src="${esc(x)}" style="width:100%;border-radius:14px;margin:6px 0">`).join('')||''}<p class="price">${money(r.price)}</p><p>${esc(r.reason)}</p>${r.reject_reason?`<div class="note">朋友意见：${esc(r.reject_reason)}</div>`:''}${r.link?`<button class="btn secondary full" id="link">查看商品</button>`:''}${r.submitter_id===state.user.id&&canResubmit(r.status)?'<button class="btn primary full" id="resubmit">重新提交</button>':''}${r.submitter_id===state.user.id&&canMarkPurchased(r.status)?'<button class="btn secondary full" id="buy">标记已购买</button>':''}`);m.querySelector('#link')?.addEventListener('click',()=>window.open(r.link,'_blank','noopener'));m.querySelector('#resubmit')?.addEventListener('click',async()=>{let p=prompt('新的价格',r.price),reason=prompt('新的购买理由',r.reason),price=parsePrice(p);if(price===null||!reason)return;await repo.resubmitRequest(id,price,reason);await notify(id,'resubmitted');m.remove();await refresh()});m.querySelector('#buy')?.addEventListener('click',async()=>{let p=parsePrice(prompt('实际购买价格',r.price));if(p===null)return;await repo.markPurchased(id,p);m.remove();await refresh()})}
async function enablePush(){try{let permission=await Notification.requestPermission();if(permission!=='granted')return render();sw=sw||await navigator.serviceWorker.ready;let sub=await sw.pushManager.getSubscription()||await subscribeForPush({registration:sw,publicKey:VAPID_PUBLIC_KEY}),s=serializeSubscription(sub);let{error}=await repo.supabase.from('push_subscriptions').upsert({user_id:state.user.id,room_id:state.room.id,endpoint:s.endpoint,p256dh:s.p256dh,auth:s.auth,user_agent:navigator.userAgent},{onConflict:'user_id,endpoint'});if(error)throw error;toast('后台通知已开启');render()}catch(e){toast(e.message||'开启失败')}}
async function notify(requestId,event){try{await repo.supabase.functions.invoke('send-shopping-notification',{body:{requestId,event}})}catch(e){console.warn('push notification failed',e)}}
boot();
